### ISSUE TITLE
v0.2.6 isn't live

### ISSUE THREAD

**Issue by brynpickering** [conda-forge/h3pandas-feedstock#12]
### Comment:

Looks like the v0.2.6 CI failed, so conda-forge doesn't include the latest version: https://github.com/conda-forge/h3pandas-feedstock/runs/18906465762

Might be sufficient re-trigger the CI? The CI failed due to a network error so might have been a one-off...

**Comment by DahnJ** [comment]
Thanks for the notification @brynpickering ! I restarted the job and indeed it now passed ✅
